# -*- coding: utf-8 -*-
"""distribution_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zcHb3y_YSm1HO65cgahqSyJLvMYFbQ16
"""

#DISTRIBUTION PLOTS
#HIST PLOT
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
tips=sns.load_dataset('tips')
tips

#plottinh univariate histogram
sns.histplot(data=tips,x='total_bill')

#displot
sns.displot(data=tips,x='total_bill',kind='hist',hue='sex',alpha=0.85)

titanic=sns.load_dataset('titanic')
titanic

sns.displot(data=titanic,x='age',kind='hist',hue='sex')

sns.displot(data=titanic,x='age',kind='hist',col='sex')

sns.kdeplot(data=tips,x='total_bill')

sns.displot(data=tips,x='total_bill',kind='kde',hue='sex',fill=True,alpha=0.924)

# sns.displot(data=tips,x='total_bill',kind='kde',hue='sex')
# sns.rugplot(data=tips,x='total_bill',)

sns.kdeplot(data=tips,x='total_bill')
sns.rugplot(data=tips,x='total_bill')

sns.histplot(data=tips,x='total_bill',y='tip')



