# -*- coding: utf-8 -*-
"""iris_svm_challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RpxilunO1KBXfaS4mO1iATMXgiTtmuC_
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

iris=sns.load_dataset('iris')
iris

#Exploratory Data Analysis
sns.pairplot(iris,hue='species')

# sns.histplot(data='iris',hue='species')

#seperating data frame first for setosa
# setosa=iris[iris['species']=='setosa']
# sns.kdeplot(setosa['sepal_width'],setosa['sepal_length'])

#Train Test Split
from sklearn.model_selection import train_test_split
X=iris[['sepal_length','sepal_width',	'petal_length','petal_width']]
y=iris['species']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

# Train a Model
from sklearn.svm import SVC
model=SVC()
model.fit(X_train,y_train)

#model evaluation
predict=model.predict(X_test)
X_test

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predict))
# cr

print(confusion_matrix(y_test,predict))











