# -*- coding: utf-8 -*-
"""matrix_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZIRmkW1e-v2AFGKSzx4zphBFnZ26wIn
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
tips=sns.load_dataset('tips')
tips

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Creating a sample DataFrame
np.random.seed(42)
data = {
    'A': np.random.rand(50),
    'B': np.random.rand(50),
    'C': np.random.choice(['Group1', 'Group2'], size=50),
    'D': np.random.choice(['X', 'Y', 'Z'], size=50)
}
df = pd.DataFrame(data)

# Selecting specific columns for plotting
selected_columns = ['A', 'B', 'C']
df_selected = df[selected_columns]

# Creating a heatmap using Seaborn
heatmap_data = df_selected.pivot_table(index='C', columns='B', values='A', aggfunc='mean')
sns.heatmap(heatmap_data)

plt.title('Heatmap of Selected Columns')
plt.show()