# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fFtXXnxkWQRueAEmpvCAqUQ535K054sN
"""

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset('tips')
tips

#scatter plot
sns.scatterplot(data=tips,x='total_bill',y='tip')
# plt.show()

sns.scatterplot(x='total_bill',y='tip',data=tips,hue='sex',style='time',size='size',alpha=0.85)

#line plot
penguin=sns.load_dataset('penguins')
penguin
lp=sns.lineplot(x='species',y='bill_length_mm',data=penguin,hue='sex',style='island',alpha=0.95)
lp
# plt.show()

#facet plot
sns.relplot(data=tips,x='total_bill',y='tip',kind='line',col='day',row='sex')