# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_Zp033z8Zt9Nc36eHlilMUT0kHIR7V3
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn.datasets import load_iris

iris=load_iris()
iris

iris.target_names

iris.feature_names

data=pd.DataFrame({'sepal length':iris.data[:,0],
 'sepal width':iris.data[:,1],
 'petal length':iris.data[:,2],
 'petal width':iris.data[:,3],
 'species':iris.target})
data

data.head()

#independent and dependednt variables
X=data[['sepal length','sepal width','petal length','petal width']]
y=data['species']

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

len(X_train)

len(X_test)

from sklearn.ensemble import RandomForestClassifier

random=RandomForestClassifier(n_estimators=100,criterion='gini')

random.fit(X_train,y_train)

X_pred=random.predict(X_test)

X_pred

random.score(X_test,y_test)

random.predict([[3,5,4,2]])





