# -*- coding: utf-8 -*-
"""recommend_system1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnkyME_OMAEKoxkx3kzHwH90CU1aTp2r
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

columns_names= ['user_id','item_id','rating','timestamp']

df = pd.read_csv('/content/u.data',sep='\t',names=columns_names)

df.head()

df.info()

df.describe()

movie_titles = pd.read_csv('/content/Movie_Id_Titles')

movie_titles.head()

df=pd.merge(df,movie_titles,on='item_id')

df.head()

sns.set_style('white')

df.groupby('title')['rating'].mean().sort_values(ascending=False).head()

df.groupby('title')['rating'].count().sort_values(ascending=False).head()

ratings=pd.DataFrame(df.groupby('title')['rating'].mean())

ratings.head()

ratings['num of rating']= pd.DataFrame(df.groupby('title')['rating'].count())

ratings.head()

ratings['num of rating'].hist(bins=70)

ratings['rating'].hist(bins=70)

sns.jointplot(x='rating',y='num of rating',data=ratings,alpha=0.85)







