# -*- coding: utf-8 -*-
"""svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pRUL_z702SbOdp8R5IJgcVV8cNaX1YG
"""

import seaborn as sns
import pandas as pd
import numpy as np

dataset=pd.read_csv('/content/IRIS.csv')

dataset

#independent and dependent variables
X=dataset[['sepal_length',	'sepal_width',	'petal_length'	,'petal_width']]
X

y=dataset['species']
y

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(len(X_train))

from sklearn.svm import SVC

model=SVC(kernel='linear')

model.fit(X_train,y_train)

model_pred=model.predict(X_test)
model_pred

# df = pd.DataFrame(model_pred, columns=['Species'])
# df
X_test

model.score(X_test,y_test)

