# -*- coding: utf-8 -*-
"""challenge_!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-0tGYySkAwhG-Wuc7oBSrQiMQDezJj6
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset('tips')
tips

sns.jointplot(data=tips,x='total_bill',y='tip',kind='reg')



