# -*- coding: utf-8 -*-
"""pair_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-0tGYySkAwhG-Wuc7oBSrQiMQDezJj6
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
temp=sns.load_dataset('tips')
temp

sns.distplot(temp['total_bill'],kde=False,bins=30)

sns.jointplot(x='total_bill',y='tip',data=temp)

sns.jointplot(x='total_bill',y='tip',data=temp)

#using hex plot
sns.jointplot(x='total_bill',y='tip',data=temp,kind='hex')

#using reg plot
sns.jointplot(x='total_bill',y='tip',data=temp,kind='reg')

iris=sns.load_dataset('iris')
iris

#pair plot
sns.pairplot(iris)



